//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using NServiceBus;
using ClassTrip.Internal.Commands.Offers;


namespace ClassTrip.Offers
{
    public partial class AcceptOfferSender : IAcceptOfferSender, ServiceMatrix.Shared.INServiceBusComponent
    {
		
        public void Send(AcceptOffer message)
        {
            ConfigureAcceptOffer(message);
            Bus.Send(message);
        }

        partial void ConfigureAcceptOffer(AcceptOffer message);

        public IBus Bus { get; set; }

    }

	
	public partial interface IAcceptOfferSender
    {
        
        void Send(AcceptOffer message);

	}

	
}
