//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NServiceBus;
using Microsoft.AspNet.SignalR;
using ClassTrip.Contracts.Offers;

namespace ClassTrip.Offers
{
	public class BroadcastOfferMade : IHandleMessages<OfferMade>
	{
		public void Handle(OfferMade message)
        {
            var context = GlobalHost.ConnectionManager.GetHubContext<OfferMadeHub>();
            context.Clients.All.offerMade(message); 
        }
	}        

}