//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NServiceBus;
using Microsoft.AspNet.SignalR;
using ClassTrip.Contracts.Offers;

namespace ClassTrip.Offers
{
	public class BroadcastRequestCompleted : IHandleMessages<RequestCompleted>
	{
		public void Handle(RequestCompleted message)
        {
            var context = GlobalHost.ConnectionManager.GetHubContext<RequestCompletedHub>();
            context.Clients.All.requestCompleted(message); 
        }
	}        

}