

//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web.Mvc;
using NServiceBus;

using ClassTrip.Internal.Commands.Offers;


using ClassTrip.Offers;
	

namespace ClassTrip.UserInterface.Controllers
{
    public partial class TestMessagesController : Controller
    {
        //
        // GET: /TestMessages/

        public ActionResult Index()
        {
            return View();
        }

				
		public IAcceptOfferSender AcceptOfferSender { get; set; }
				
		public IRequestOfferSender RequestOfferSender { get; set; }
		
        // POST: /TestMessages/SendMessageAcceptOffer
          
        [HttpPost]
        public string SendMessageAcceptOffer(AcceptOffer AcceptOffer)
        {
            ConfigureAcceptOffer(AcceptOffer);
            AcceptOfferSender.Send(AcceptOffer);
			return "<p> AcceptOffer command sent</p>";
        }
		
        // POST: /TestMessages/SendMessageRequestOffer
          
        [HttpPost]
        public string SendMessageRequestOffer(RequestOffer RequestOffer)
        {
            ConfigureRequestOffer(RequestOffer);
            RequestOfferSender.Send(RequestOffer);
			return "<p> RequestOffer command sent</p>";
        }
		
	  


	  // Send Commands
    
        partial void ConfigureAcceptOffer(AcceptOffer message);
      
        partial void ConfigureRequestOffer(RequestOffer message);
      
	 // Publish Events
        }
}
