//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by ServiceMatrix.
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using NServiceBus;
using ClassTrip.Internal.Commands.Offers;
using ClassTrip.Contracts.Offers;


namespace ClassTrip.Offers
{
    public partial class OfferRequestedHandler : IOfferRequestedHandler, ServiceMatrix.Shared.INServiceBusComponent, IHandleMessages<OfferRequested>
    {
		
		public void Handle(OfferRequested message)
		{
			// Handle message on partial class
			this.HandleImplementation(message);
		}

		partial void HandleImplementation(OfferRequested message);

        public void Send(MakeOffer message)
        {
            ConfigureMakeOffer(message);
            Bus.Send(message);
        }

        partial void ConfigureMakeOffer(MakeOffer message);

        public IBus Bus { get; set; }

    }

	
	public partial interface IOfferRequestedHandler
    {
        
        void Send(MakeOffer message);

	}

	
}
